name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    if: true # false to skip job during debug
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18", "1.21"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: |
          go mod tidy
          go version

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: go test -v -cover ./...
